### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by Valeros03** [thevickypedia/Jarvis#34]
**Describe the bug**
Hi I got this error message when I try to launch it from a py file that looks like this:
import jarvis

if __name__ == '__main__':
    jarvis.start()

Before I got another error message here(file models.py, line 93):

if not env.recognizer_settings and not env.phrase.limit:
        env.recognizer_settings = RecognizerSettings()  

it was like:
Traceback (most recent call last):
  File "C:\Users\sebyf\Desktop\Jarv.py", line 1, in <module>
    import jarvis
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\__init__.py", line 27, in <module>
    from ._preexec import keywords_handler  # noqa: F401
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\_preexec\keywords_handler.py", line 9, in <module>
    from jarvis.modules.conditions import conversation, keywords
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\modules\conditions\conversation.py", line 11, in <module>
    from jarvis.modules.models import models
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\modules\models\models.py", line 272, in <module>
    _main_process_validations()
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\modules\models\models.py", line 93, in _main_process_validations
    if not env.recognizer_settings and not env.phrase.limit:
AttributeError: 'EnvConfig' object has no attribute 'phrase'

than I tried to remove that condition and I got:

Traceback (most recent call last):
  File "C:\Users\sebyf\Desktop\Jarv.py", line 1, in <module>
    import jarvis
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\__init__.py", line 27, in <module>
    from ._preexec import keywords_handler  # noqa: F401
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\_preexec\keywords_handler.py", line 9, in <module>
    from jarvis.modules.conditions import conversation, keywords
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\modules\conditions\conversation.py", line 11, in <module>
    from jarvis.modules.models import models
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\modules\models\models.py", line 272, in <module>
    _main_process_validations()
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\modules\models\models.py", line 119, in _main_process_validations
    db = database.Database(database=fileio.base_db)
  File "C:\Users\sebyf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jarvis\modules\database\database.py", line 33, in __init__
    self.connection = sqlite3.connect(database=database, check_same_thread=False, timeout=timeout)
sqlite3.OperationalError: unable to open database file

**Comment by thevickypedia** [comment]
I'm not sure which version you're running or how (pypi or directly downloaded from Git)!
In either case the error `AttributeError: 'EnvConfig' object has no attribute 'phrase'` seems to be incorrect
The attribute has always been `phrase_limit` and more recently its named as `listener_phrase_limit`
If you installed it via pypi, I'd recommend running the below

```shell
python3 -m pip uninstall --no-cache-dir jarvis-ironman
python3 -m pip install --no-cache --upgrade jarvis-ironman
```

As for the SQL error `sqlite3.OperationalError: unable to open database file`, it may be because your IDE/terminal is lacking permissions to the repo/DB file. Please update your folder permissions accordingly.

Let me know if you still face the `sqlite3.OperationalError: unable to open database file` error, and which windows version you are using. I can try pushing out a new version with `fileio` attributes having the absolute path instead of the current relative ones.

**Comment by Valeros03** [comment]
Hi, I'm using the pypi version on Windows 11. The `AttributeError: 'EnvConfig' object has no attribute 'phrase'` error is solved (I just use the new name `listener_phrase_limit` instead of `phrase_limit`.
In the other hand for the error `sqlite3.OperationalError: unable to open database file` I discovered two things actually:

1. inside models.py file, line 119, `db = database.Database(database=fileio.base_db)` is trying to call base_db from fileio module, but inside fileio.py there's not such a function or class called in this way (but actually the interpreter does not say anything about that, so I guess it works just fine)
2. I put a simple debug line `print(str(fileio.base_db))` (inside models.py, before `db = database.Database(database=fileio.base_db)` and I discovered that is trying to reach out a file named database.db inside fileio folder, but there's not a folder named fileio inside jarvis directory.
So I guess I'm missing something to install/to do.

**Comment by thevickypedia** [comment]
You're right, I must have removed the `fileio` directory creation when I reformatted the logging
Thanks for bringing this up. I found more than 1 bug when I was digging into it. Much appreciated.
I'm releasing a new version ASAP to fix this.

**Comment by thevickypedia** [comment]
Please go ahead and redo 
```shell
python3 -m pip uninstall --no-cache-dir jarvis-ironman
python3 -m pip install --no-cache --upgrade jarvis-ironman
```
The issue should be addressed in [v3.3](https://github.com/thevickypedia/Jarvis/releases/tag/v3.3)

**Comment by Valeros03** [comment]
Ok now the application is working but I still need to use `listener_phrase_limiter`. However I got some other errors and a question; should I open a new Issue ticket(I guess are not much related to the previous errors)? Nevertheless I'm glad to help in anyway I can, I'm still a student, but I realy like this project and the idea of a remote AI vocal controller.

**Comment by thevickypedia** [comment]
@Valeros03 You may create a new issue, I'm closing this as done
I appreciate your help in making this library better. Until recently, I was testing the package with multiple operating systems, with and without all the setup requirements before releasing a new version. But it has gotten so big that testing takes away a lot of time, so I gave up on them. Guess that has made some versions unstable.
I'll look forward to the new issue. Thank you.
